export { AboutHeroSection } from "./AboutHeroSection";
export { AboutWelcomeSection, AboutPhilosophySection } from "./AboutPhilosophySection";
export { AboutApproachSection } from "./AboutApproachSection";
export { AboutSkincareSection, AboutValuesSection } from "./AboutValuesSection";
export { AboutClinicSection, AboutSanctuarySection } from "./AboutSanctuarySection";
export { AboutAchievementsSection, AboutMilestonesSection } from "./AboutMilestonesSection";
export { AboutCtaSection } from "./AboutCtaSection";
export { AboutTeamSection } from "./AboutTeamSection";
export { AboutTeamDescSection, AboutCarePromiseSection } from "./AboutCarePromiseSection";
export { AboutContactSection } from "./AboutContactSection";
export { AboutMapSection } from "./AboutMapSection";
export { AboutSocialSection } from "./AboutSocialSection";
export { AboutNewsletterSection } from "./AboutNewsletterSection";
